### PR TITLE
Always set 'RunAsNonRoot' explicitly on init container

### LINKED ISSUE #1894: install-oneagent container breaks non-root policy
**Describe the bug**
We're deploying [istio-cni](https://istio.io/latest/docs/setup/additional-setup/cni/) that comes with the following pod security context:
```yaml
securityContext:
  fsGroup: 2000
  runAsGroup: 3000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
```
Dynatrace injects the install-oneagent container with the following container security context:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0
```

It should also have `runAsNonRoot: false` so that we don't see the following error:
```bash
message: 'container''s runAsUser breaks non-root policy (pod: "istio-cni-node-ghjgn_istio-system(c7fa6210-a40f-40d9-b838-67aae08fa039)", container: install-oneagent)'
```

**To Reproduce**
1. Create a pod with above pod and security context

**Expected behavior**
Dynatrace injection should work with runAsNonRoot pods. Maybe the injected security context could simply be customized via the helm chart.

**Additional context**
K8s: v1.24.13
Istio: 1.17.2

### PR DESCRIPTION
**Pull request by albertogdd**
Fix #1894 

## Description

Always set `RunAsNonRoot` explicitly on webhook's init container. Before it was only set when its value was `true`.
This caused `Init:CreateContainerConfigError` status on some cases.

## How to reproduce this
- Deploy the operator in cloudNativeFullStack or applicationMonitoring
- Deploy the deployment sample below
- Check the pods status (kubectl get pod php-musl-.. -n sample -o yaml
- See the error message

<details>
<summary>Deployment sample</summary>

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-musl
  name: 02-php-musl
  namespace: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-musl
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/technologies: php
        oneagent.dynatrace.com/flavor: musl
        oneagent.dynatrace.com/failure-policy: fail
      labels:
        app: php-musl
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - image: docker.io/php:fpm-alpine
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 9000
            initialDelaySeconds: 600
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          name: app
          env:
            - name: DT_DEBUGFLAGS
              value: debugBootstrapNative=true
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            tcpSocket:
              port: 9000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

</details>

## Checklist
- [x] Unit tests have been updated/added
- [x] PR is labeled accordingly with a single label
- [x] I have read and understood the [contribution guidelines](https://github.com/Dynatrace/dynatrace-operator/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by albertogdd** [comment]
WIP: Fixing unit tests

File: src/webhook/mutation/pod_mutator/pod_mutator_test.go [hunk 1]
```diff
@@ -155,7 +155,7 @@ func TestHandlePodMutation(t *testing.T) {
 		require.NotNil(t, initSecurityContext.ReadOnlyRootFilesystem)
 		assert.True(t, *initSecurityContext.ReadOnlyRootFilesystem)
 
-		assert.Nil(t, initSecurityContext.RunAsNonRoot)
+		assert.NotNil(t, initSecurityContext.RunAsNonRoot)
```
Comment (albertogdd) [inline src/webhook/mutation/pod_mutator/pod_mutator_test.go:159]: As mentioned in the daily, when doing assert.True here it would pass when running the single unit test but fail when running all the package ones :clown_face:

Comment (albertogdd) [reply src/webhook/mutation/pod_mutator/pod_mutator_test.go]: Fixed

Comment (0sewa0) [reply src/webhook/mutation/pod_mutator/pod_mutator_test.go]: yes its veeery weird,

I think I found the problem, find 
```
func getTestPod() *corev1.Pod {
```

and make it 
```
func getTestPod() corev1.Pod {
```

Comment (0sewa0) [reply src/webhook/mutation/pod_mutator/pod_mutator_test.go]: don't ask me why this is the problem 😅 

(also bunch of things will be red after the change, but fixing them is simple)

Comment (albertogdd) [reply src/webhook/mutation/pod_mutator/pod_mutator_test.go]: Yes I thought about doing something similar!
I will refactor it in a new commit, thanks for checking :+1:

Comment (albertogdd) [reply src/webhook/mutation/pod_mutator/pod_mutator_test.go]: @0sewa0 I tried it out and the end behavior is the same... Which makes sense because in getTestPod() the struct gets instantiated anyways whether you return it as reference or value.

**Review by 0sewa0 — APPROVED** [review]
